# Generated by Django 4.2.7 on 2023-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('priority_level', models.CharField(max_length=200)),
                ('date_posted', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
