# Generated by Django 4.2.7 on 2023-12-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emplyee_id',
            new_name='employee_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='skill_set',
            field=models.TextField(),
        ),
    ]
