# Generated by Django 4.2.7 on 2023-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_emplyee_id_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='', upload_to='employees/profiles'),
        ),
    ]
