# Generated by Django 4.2.7 on 2023-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='incomplete', max_length=200),
        ),
    ]
